export interface TocItem {
  id: string
  text: string
  level: number
}

export function extractToc(html: string): TocItem[] {
  const items: TocItem[] = []
  // Match h2 and h3 tags with id attributes generated by rehype-slug
  // rehype-autolink-headings with behavior:'wrap' produces: <h2 id="x"><a href="#x">text</a></h2>
  const regex = /<h([23])\s+id="([^"]+)"[^>]*><a[^>]*>([^<]*)<\/a><\/h[23]>/g
  let match

  while ((match = regex.exec(html)) !== null) {
    items.push({
      level: parseInt(match[1], 10),
      id: match[2],
      text: match[3].trim(),
    })
  }

  return items
}
